theme: jekyll-theme-minimal
title: Moving Designs
description: Somewhere for projects I'm working on

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  
minima:
  skin: dark

header_pages:
  - index.md

# show_excerpts: true
